//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::brewer::Entity as Brewer;
pub use super::recipe::Entity as Recipe;
pub use super::roast::Entity as Roast;
pub use super::tag::Entity as Tag;
pub use super::tag_recipe::Entity as TagRecipe;
pub use super::user::Entity as User;
